### PR TITLE
is210-week-04-warmup

### PR DESCRIPTION
**Pull request by xiangyq**

### CODE REVIEW

**Comment by xiangyq** [comment]
what is the result? pass or not?

**Comment by cheuschober** [comment]
@xiangyq, That's a bit odd. I would have expected jenkins to work. I'll resolve this shortly.

**Comment by cheuschober** [comment]
retest this please

**Comment by cheuschober** [comment]
@xiangyq, the Jenkins server might have been undergoing its nightly maintenance when you submitted. Either way you can run your tests locally using the `runtests.sh` script which will give you the same results without having to submit.

**Comment by xiangyq** [comment]
I am glad I got this done. For some reason, I can not watch your youtube videos in China. And speed is so slow.

**Comment by xiangyq** [comment]
Dear Professor:
For some reason I had two pull requests this time. And I submitted the wrong one on Blackboard. 
https://github.com/is210-2015-spring-01/is210-week-04-warmup/pull/1     ----- I passed this one.
Can I change this on Blackboard?

**Comment by cheuschober** [comment]
@xiangyq, 

Yup. Just make a second submission on Blackboard!

**Comment by cheuschober** [comment]
retest this please

**Comment by xiangyq** [comment]
Great! I passed! I have some trouble with internet right now. Speed is so slow.

**Pull request merged**
